version: 2

defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  working_directory: ~/project

prepare_conda: &prepare_build
  run:
    name: Prepares the project build
    command: |
      apt-get -y install make
      apt-get -y install g++
      conda create -n "maka_paper" python==3.7.9 -y
      source activate maka_paper
      conda install -c conda-forge jsonnet -y
      pip install -r Transparency/requirements.txt
      python -m spacy download en
      conda install -c anaconda jupyter -y
      conda install -c anaconda pytest -y

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *prepare_build
