version: 2

defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  working_directory: ~/project

prepare_conda: &prepare_conda
  run:
    name: Prepare and activate the conda environment
    command: |
    conda create -n "maka_paper" python==3.7.9
    conda activate maka_paper

jobs:
  build: 
    <<: *defaults
    steps:
      - *prepare_conda
