#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --job-name=PreprocessQQP
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=03:00:00
#SBATCH --mem=32000M

module purge
module load 2019
module load Anaconda3/2018.12

# Go to the script dir
cd $HOME/Transparency/Transparency/preprocess/SNLI

# Activate your environment
source activate fact_paper

# Run the script and preprocess the dataset
ipython SNLI.py
